name: CI/CD QAbuild
on:
  push:
    branches:
      - QA-Testing   
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Test Reporter
        uses: dorny/test-reporter@v1.5.0
        with:
          name: Run Tests
          path: "**/surefire-reports/TEST-*.xml"
          reporter: java-junit
      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
           name: artifact
           path: 'target/deploymentValidation-1.0-SNAPSHOT.jar'
